import requests
import variable


print("===========================")
print()
api_key = str(input("api_key = "))
api_secret = str(input("api_secret = "))
token = str(input("token = "))
print()
print("==============================")
print()
tr = input("TRACKER with symbol = " )
asset_TR = tr.upper()
print()
print(">>>>>","15m","30m","1h","2h","4h","6h","8h","12h","1d")
ind_t = input("INDICATOR Timeframe = " )
print()
print("==============================")
print()
print("BTC MODEL = 5,10,40,65")
print()
e1 = input("add EMA NO.1 = ")
e2 = input("add EMA NO.2 = ")
e3 = input("add EMA NO.3 = ")
e4 = input("add EMA NO.4 = ")
print()
print("==============================")
print()
r = input("add RSI Length = ")
print()
print("==============================")
print()
print("MODEL = length20,std2")
print()
b1 = input("add BBAND Length = ")
b2 = input("add BBAND std = ")
print()
print("==============================")
print()
print("BTC MODEL = fast12,slow16,signal10")
print()
m1 = input("add MACD fast = ")
m2 = input("add MACD slow = ")
m3 = input("add MACD signal = ")
print()
print("==============================")
print()
print("BTC MODEL = length10,rsi14,k8,d5")
print()
s1 = input("add MACD length = ")
s2 = input("add MACD rsi = ")
s3 = input("add MACD k = ")
s4 = input("add MACD d = ")
print()
print("==============================")
print()
td = input("sleep date = ")
th = input("sleep hours = ")
tm = input("sleep mins = ")
ts = input("sleep secs = ")
print()
print("==============================")
print()

progress = input("DO YOU WANT TO PROGRESS ROBOT ?  ( Y / N ) ")
if progress == "y":

    data_base = str("/"+api_key+"/"+api_secret+"/"+token+"/"+asset_TR+"/"+ind_t+"/"+e1+"/"+e2+"/"+e3+"/"+e4+"/"+r+"/"+b1+"/"+b2+"/"+m1+"/"+m2+"/"+m3+"/"+s1+"/"+s2+"/"+s3+"/"+s4+"/"+td+"/"+th+"/"+tm+"/"+ts+"/"+"0"+"/"+"0") 
    requests.post(url=variable.domain+"/"+"ROBOT_STOP"+data_base)

else :
    print("ROBOT_STOP")
